[package]
name = "rustboy"
version = "0.1.0"
edition = "2021"
authors = ["Matheus T. dos Santos <matheuswhite1@protonmail.com>", "José Gomes <>", "Paulo Roberto <>", "Victor Miranda <>"]

[lib]
name = "rustboy"
path = "src/lib.rs"

[[bin]]
name = "rustboy"
path = "src/bin.rs"

[dependencies]
